[versions]
# plugins
kotlin = "1.8.21"
gradleIntelliJPlugin = "1.17.3"
compose = "1.6.10-dev1584"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }